# Generated by Django 4.2.5 on 2023-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_remove_robot_serial_alter_robot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
